main:
  - "mtscATAC"
  - "mtpreproc"
  - "multiplex"
  - "clones"
  - "enrichment"
  - "DE"


genome_path:
  #genome: "MTBlacklist" # ["MTBlacklist", "MTBlacklist_mtasnucl", "noblacklist_hg38"]
  MTBlacklist:
    # Genome paths
    genome_dir: "/data/isshamie/mito_lineage/data/external/GRCh38_MT_blacklist/" #"/data2/mito_lineage/data/external/GRCh38_MT_blacklist/" #
    ref_fa: "/data2/mito_lineage/data/external/GRCh38_MT_blacklist/fasta/genome.fa" # I'm pretty sure this and genome_dir are the same and I just moved it.
    mt_ref_fa: "/data2/mito_lineage/data/external/GRCh38_MT_blacklist/chrM.fasta"
  MTblacklist_mtasnucl:
    # Genome paths
    genome_dir: "/data/isshamie/mito_lineage/data/external/GRCh38_MT_blacklist/" #"/data2/mito_lineage/data/external/GRCh38_MT_blacklist/" #
    ref_fa: "/data2/mito_lineage/data/external/GRCh38_MT_blacklist/fasta/genome.fa" # I'm pretty sure this and genome_dir are the same and I just moved it.
    mt_ref_fa: "/data2/mito_lineage/data/external/GRCh38_MT_blacklist/chrM.fasta"

mtpreproc:
  params:
    cellrbc: [True]
    numreadsfilter: [200]
    basequality: [20]
  mito_character: "chrM"
  maxBP: 16571

# For constructing the af_by_cell filter position_filter:
filters:
  params:
    mincells: [10]
    minreads: [50]
    topN: [0]
    hetthresh: [0.001]
    minhetcells: [10] #[10,5]
    hetcountthresh: [5] #[5,2]
    bqthresh: [20]


mgatk:
  params:
    lowcovthresh: 2 # For mgatk to fill in low coverage cell positions
    ncellsthresh: 5
  chrM_refAllele: "/data2/mito_lineage/data/external/chrM_refAllele.txt"


multiplex:
  #params:
  pseudo_multiplex:
    #Number Reads Total: 10000000
    num_cells: 100000 # high enough to choose all
    is_proportional: False
  genome_size: "/data/isshamie/mito_lineage/data/external/GRCh38_MT_blacklist/fasta/genome.chrom.size"

  mt:
    minMAF:
      - 0.01
    minCOUNT:
      - 200

clones:
  variants:
    - "simple" # Old one, where the depth is not filled in and uses the union of the vireo vcfs
    - "mgatkdonor" # reruns mgatk on the donors, takes the intersection of the filtered data
    #- "simpleintersection" #Union of the vireo output vcfs, so doesn't re-run mgatk.
  method:
    - "vireo" #["vireo", "phylogeny", "knn"]
  vireo:
    params:
      nclonelist: [20, 40, 100]
  phylogeny:
    params:
      method: "missingV"
      afthresh: 0
      dpthresh: 2
  knn:
    params:
      resolution: [10,3]

annotations:
  datadir: "/data2/mito_lineage/data/external/granja_cd34/"
  ID: "GSE129785_scATAC-Hematopoiesis-CD34"
  name: "granja_cd34"
  #file: "granja_published_C1.rds"

  method:
    - "lareau"
    - "anchors"
  lareau:
    proj_ref: "sample" #sample, ref . Which experiment to run lsi on for the coordinate space
  anchors:
    assay:
      - "RNA"
      - "ATAC"

