alabaster==0.7.10
anaconda-client==1.6.3
anaconda-navigator==1.8.4
anaconda-project==0.6.0
ann-solo==0.1.3
annoy==1.15.1
argcomplete==1.9.4
argh==0.26.2
asn1crypto==0.22.0
astroid==1.4.9
astropy==2.0.7
Babel==2.4.0
backports-abc==0.5
backports.functools-lru-cache==1.6.1
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.4.0.2
beautifulsoup4==4.6.0
biograpy==1.0b0.dev0
biopython==1.72
bitarray==0.8.1
blaze==0.10.1
bleach==1.5.0
bokeh==0.12.5
boto==2.46.1
Bottleneck==1.2.1
brewer2mpl==1.4.1
bz2file==0.98
cdecimal==2.3
certifi==2019.6.16
cffi==1.10.0
chardet==3.0.3
Circos==1.3.5
click==6.7
cloudpickle==0.2.2
clyent==1.2.2
colorama==0.3.9
colormath==2.1.1
conda==4.7.10
conda-package-handling==1.3.11
ConfigArgParse==0.14.0
configparser==3.5.0
contextlib2==0.5.5
cooler==0.7.6
cryptography==2.5
cutadapt==1.16
cycler==0.10.0
Cython==0.29.6
cytoolz==0.8.2
dask==0.18.1
datashape==0.5.4
decorator==4.3.0
deepTools==3.1.0
dill==0.2.8.2
distributed==1.16.3
docutils==0.13.1
entrypoints==0.2.2
enum34==1.1.6
et-xmlfile==1.0.1
fastcache==1.0.2
feather-format==0.4.0
Flask==0.12.2
Flask-Cors==3.0.2
funcsigs==1.0.2
functools32==3.2.3.post2
future==0.16.0
futures==3.1.1
gevent==1.2.1
gffutils==0.9
graphviz==0.11.1
greenlet==0.4.12
grin==1.2.1
gtracks==1.0.17
h5py==2.7.0
hdbscan==0.8.19
HeapDict==1.0.0
HiCExplorer==2.1.4
html5lib==0.999
idna==2.5
imageio==2.3.0
imagesize==0.7.1
intervaltree==2.1.0
ipaddress==1.0.18
ipykernel==4.6.1
ipyparallel==6.0.2
ipython==5.3.0
ipython-genutils==0.2.0
ipywidgets==6.0.0
isort==4.2.5
itsdangerous==0.24
jdcal==1.3
jedi==0.10.2
Jinja2==2.9.6
joblib==0.11
jsonschema==2.6.0
jupyter-client==5.0.1
jupyter-console==5.1.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.0
jupyter-core==4.3.0
jupyter-highlight-selected-word==0.1.1
jupyter-latex-envs==1.4.4
jupyter-nbextensions-configurator==0.4.0
jupyterlab==0.31.12
jupyterlab-launcher==0.10.5
kiwisolver==1.1.0
lazy-object-proxy==1.2.2
libarchive-c==2.8
llvmlite==0.23.0
locket==0.2.0
lockfile==0.12.2
luigi==2.7.8
lxml==4.3.1
lzstring==1.0.3
Markdown==2.6.11
MarkupSafe==0.23
matplotlib==2.2.4
matplotlib-venn==0.11.5
mistune==0.7.4
mkl-fft==1.0.2
mkl-random==1.0.1
MonoVar==0.0.0
mpmath==0.19
msgpack-python==0.4.8
multipledispatch==0.4.9
multiprocess==0.70.5
multiqc==1.3
natsort==5.1.1
navigator-updater==0.2.0
nbconvert==5.1.1
nbformat==4.3.0
network-evaluation-tools==1.0.2
networkx==1.11
nltk==3.2.3
nose==1.3.7
notebook==5.0.0
numba==0.38.1
numexpr==2.6.5
numpy==1.16.6
numpydoc==0.6.0
odo==0.5.0
olefile==0.44
openpyxl==2.4.7
packaging==16.8
pandarallel==0.1.7
pandas==0.24.2
pandocfilters==1.4.1
partd==0.3.8
pathlib==1.0.1
pathlib2==2.2.1
patsy==0.4.1
pep8==1.7.0
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.3.0
plotly==2.7.0
ply==3.10
prompt-toolkit==1.0.14
psutil==5.2.2
ptyprocess==0.5.1
py==1.4.33
py2bit==0.3.0
pyarrow==0.14.1
pybedtools==0.7.10
pyBigWig==0.3.11
pycairo==1.10.0
pycodestyle==2.4.0
pycosat==0.6.3
pycparser==2.17
pycrypto==2.6.1
pycurl==7.43.0.2
pyfaidx==0.5.4.1
pyflakes==1.5.0
pyGenomeTracks==2.0
Pygments==2.2.0
pygraphviz==1.5
pylint==1.6.4
pyodbc==4.0.16
pyOpenSSL==17.0.0
pypairix==0.3.6
pyparsing==2.4.6
pysam==0.14.1
PySocks==1.6.8
pyteomics==4.1
pytest==3.0.7
pytest-ipynb==1.1.0
python-daemon==2.2.0
python-dateutil==2.8.1
python-dotenv==0.10.3
python-igraph==0.7.1.post6
pytz==2019.3
PyUpSet==0.1.1.post7
PyWavelets==0.5.2
PyYAML==3.13
pyzmq==16.0.2
QtAwesome==0.4.4
qtconsole==4.4.3
QtPy==1.2.1
requests==2.21.0
rope==0.9.4
ruamel-yaml==0.15.71
ruffus==2.6.3
runipy==0.1.5
sarge==0.1.4
scandir==1.5
scikit-image==0.14.0
scikit-learn==0.19.1
scipy==1.2.3
seaborn==0.9.1
-e git+https://github.com/LewisLabUCSD/secretoryDB.git@9e65d3a81e7151a9f8d82e38c191a0873368c931#egg=secretorydb
simplegeneric==0.8.1
simplejson==3.13.2
singledispatch==3.4.0.3
six==1.14.0
snowballstemmer==1.2.1
sortedcollections==0.5.3
sortedcontainers==1.5.7
spectra==0.0.9
Sphinx==1.5.6
spyder==3.1.4
SQLAlchemy==1.1.9
-e git+https://github.com/isshamie/Neutrophil-Time-Series.git@5952d7cc7131d5944c52ccacf141ef3967487bec#egg=src
statsmodels==0.9.0
subprocess32==3.5.4
sympy==1.0
tables==3.4.2
tblib==1.3.2
terminado==0.6
testpath==0.3
toolz==0.8.2
tornado==4.5.1
tqdm==4.35.0
traitlets==4.3.2
-e git+https://github.com/isshamie/CH_TSS.git@c98c3e51d43fae0ebe2a1e8662b9c66eb658bd96#egg=tss&subdirectory=TSS_code
typing==3.7.4
unicodecsv==0.14.1
Unidecode==1.0.22
urllib3==1.24.1
version-information==1.0.3
wcwidth==0.1.7
Werkzeug==0.12.2
widgetsnbextension==2.0.0
wrapt==1.10.10
xlrd==1.0.0
XlsxWriter==0.9.6
xlwt==1.2.0
xmltramp2==3.1.1
xopen==0.3.3
yapf==0.22.0
zict==0.1.2
