---
BedFile: /data2/mito_lineage/data/processed/amplicons/MT_amplicons.bed
#isPcrBinary: # isPcr
TwoBitFile: /data2/mito_lineage/data/processed/genomes/refdata-cellranger-GRCh38-3.0.0/MT.bit #hg38.2bit
MpdBinary: /data2/isshamie/mito_lineage/external/mpd-c/bin/mpd
MpdIdx: /data2/mito_lineage/data/processed/genomes/refdata-cellranger-GRCh38-3.0.0/MT_index.sdx
dbSnpIdx: /data2/mito_lineage/data/processed/genomes/refdata-cellranger-GRCh38-3.0.0/ds_flat.sdx #ds_flat.sdx

CoverageThreshold: 0.8
PrimerSizeMin: 17
PrimerSizeMax: 27
PadSize: 60
PoolMax: 10
PoolMin: 5

AmpSizeMax: 175
AmpSizeMin: 120
TmMax: 62
TmMin: 57
GcMax: 0.7
GcMin: 0.3

Iter: 4
IncrTm: 1
IncrTmStep: 1
IncrAmpSize: 10
