global: "PROJECT"

indir: "/data2/isshamie/mito_lineage/data/processed/mtscATAC/jan21_2021/MTblacklist"
experiment: "jan21_2021"
genome: "MTblacklist"

chip_genes: ["TP53", "U2AF1", "SF3B1", "SRSF2", "TET2", "IDH1", "IDH2"]

samples:
  - "J2"
  - "P2"
